export default [
    {
        model: 'salesforce.school',
        pk: 660628,
        fields: {
            salesforce_id: '001U000001Nr19oIAB',
            name: 'New Albany High School',
            phone: '(812) 542-8506',
            website: 'nahs.nafcs.k12.in.us/',
            type: 'High School',
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: null,
            pell_grant_recipients: null,
            percent_students_pell_grant: null,
            current_year_students: '0.0',
            all_time_students: '424.0',
            total_school_enrollment: null,
            current_year_savings: '0.000',
            all_time_savings: '8995.960',
            physical_country: 'United States',
            physical_street: '1020 Vincennes Street',
            physical_city: 'New Albany',
            physical_state_province: 'Indiana',
            physical_zip_postal_code: '47150',
            long: '-85.812',
            lat: '38.298'
        }
    },
    {
        model: 'salesforce.school',
        pk: 666546,
        fields: {
            salesforce_id: '0016f00002ZF2EzAAL',
            name: 'New Albany High School,OH',
            phone: '614.413.8300',
            website: 'https://www.napls.us/Page/15',
            type: 'High School',
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: null,
            pell_grant_recipients: null,
            percent_students_pell_grant: null,
            current_year_students: '0.0',
            all_time_students: '380.0',
            total_school_enrollment: null,
            current_year_savings: '0.000',
            all_time_savings: '17139.900',
            physical_country: 'United States',
            physical_street: '7600 Fodor Rd.',
            physical_city: 'New Albany',
            physical_state_province: 'Ohio',
            physical_zip_postal_code: '43054',
            long: '-82.815',
            lat: '40.085'
        }
    },
    {
        model: 'salesforce.school',
        pk: 671972,
        fields: {
            salesforce_id: '0016f00002dhEGIAA2',
            name: 'New Albany High School',
            phone: '(662) 534-1805',
            website: null,
            type: 'High School',
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: null,
            pell_grant_recipients: null,
            percent_students_pell_grant: null,
            current_year_students: '50.0',
            all_time_students: '50.0',
            total_school_enrollment: null,
            current_year_savings: '3968.500',
            all_time_savings: '3968.500',
            physical_country: 'United States',
            physical_street: '201 Highway 15 North',
            physical_city: 'New Albany',
            physical_state_province: 'Mississippi',
            physical_zip_postal_code: '38652',
            long: '-88.998',
            lat: '34.486'
        }
    },
    {
        model: 'salesforce.school',
        pk: 664178,
        fields: {
            salesforce_id: '0010B00001wAN2hQAG',
            name: 'NEW ALBANY PLAIN LOCAL SCHOOLS',
            phone: '(614) 855-2040',
            website: 'www.napls.us',
            type: 'K-12 School',
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: null,
            pell_grant_recipients: null,
            percent_students_pell_grant: null,
            current_year_students: '0.0',
            all_time_students: '370.0',
            total_school_enrollment: null,
            current_year_savings: '0.000',
            all_time_savings: '24844.500',
            physical_country: 'United States',
            physical_street: '55 NORTH HIGH STREET',
            physical_city: 'NEW ALBANY',
            physical_state_province: 'Ohio',
            physical_zip_postal_code: '43054',
            long: '-82.810',
            lat: '40.084'
        }
    },
    {
        model: 'salesforce.school',
        pk: 661959,
        fields: {
            salesforce_id: '0016f00002dgyWXAAY',
            name: 'Indiana University, Southeast',
            phone: '(812) 941-2333',
            website: 'https://ius.edu/',
            type: 'College/University (4)',
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: '6588.0',
            pell_grant_recipients: '2306.0',
            percent_students_pell_grant: '35.0',
            current_year_students: '70.0',
            all_time_students: '166.0',
            total_school_enrollment: null,
            current_year_savings: '5555.900',
            all_time_savings: '13175.420',
            physical_country: 'United States',
            physical_street: '4201 Grant Line Rd',
            physical_city: 'New Albany',
            physical_state_province: 'Indiana',
            physical_zip_postal_code: '47150',
            long: '-85.820',
            lat: '38.343'
        }
    },
    {
        model: 'salesforce.school',
        pk: 658732,
        fields: {
            salesforce_id: '001U0000007gjZdIAI',
            name: 'Indiana University Southeast',
            phone: '(812) 941-2333',
            website: 'http://www.ius.edu/chemistry/',
            type: 'College/University (4)',
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: '6061.0',
            pell_grant_recipients: '2570.0',
            percent_students_pell_grant: '42.0',
            current_year_students: '90.0',
            all_time_students: '3213.0',
            total_school_enrollment: '5419.0',
            current_year_savings: '7143.300',
            all_time_savings: '271182.210',
            physical_country: 'United States',
            physical_street: '4201 Grant Line Rd',
            physical_city: 'New Albany',
            physical_state_province: 'Indiana',
            physical_zip_postal_code: '47150',
            long: '',
            lat: ''
        }
    },
    {
        model: 'salesforce.school',
        pk: 673227,
        fields: {
            salesforce_id: '0010B000023aqmLQAQ',
            name: 'Union County School District',
            phone: '662-534-1960',
            website: 'http://www.union.k12.ms.us/',
            type: null,
            location: 'Domestic',
            adoption_date: null,
            key_institutional_partner: false,
            achieving_the_dream_school: false,
            hbcu: false,
            texas_higher_ed: false,
            undergraduate_enrollment: null,
            pell_grant_recipients: null,
            percent_students_pell_grant: null,
            current_year_students: '70.0',
            all_time_students: '70.0',
            total_school_enrollment: null,
            current_year_savings: '5555.900',
            all_time_savings: '5555.900',
            physical_country: 'United States',
            physical_street: '250 Carter Ave',
            physical_city: 'New Albany',
            physical_state_province: 'Mississippi',
            physical_zip_postal_code: '38652',
            long: '-89.011',
            lat: '34.493',
            testimonial: 'this is my testimonial',
            testimonial_name: 'Fake Person',
            testimonial_position: 'Phony Professor'
        }
    }
];
