#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

try npm run-script build
do_progress "Removing temporary build files" \
  find ./dist/app -type f -not -name '*.css' -delete

/bin/rm -f ./dist/settings*.js*

try "$(npm bin)/node-sass" --source-map true --source-map-contents true \
--output dist/styles/ \
--include-path ./node_modules \
src/styles/main.scss
