#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

rm -rf dist
try "$(npm bin)/gulp"
do_progress "Removing temporary build files" \
  /bin/rm -r ./dist/settings-example*

try "$(npm bin)/node-sass" --source-map true --source-map-contents true \
--output dist/styles/ \
--include-path ./node_modules \
src/styles/main.scss
