#!/bin/bash

cd "$(dirname "$0")/.."

[[ -f ./node_modules/ ]] && rm -rf ./node_modules/
[[ -f ./jspm_packages/ ]] && rm -rf ./jspm_packages/
[[ -f ./vendor/ ]] && rm -rf ./vendor/
[[ -f ./dist/ ]] && rm -rf ./dist/
[[ -f ./coverage/ ]] && rm -rf ./coverage/
