#!/usr/bin/env node

'use strict'

// Open .nyc_output/*.json and adjust the path in each JSON file because nyc
// does not seem to be able to find the source file otherwise.
//
// Apparently setting the path to be `src/ANYTHING_GOES_HERE` is sufficient for
// the source maps to be loaded when generating the coverage report

const fs = require('fs')
const path = require('path')

const NYC_OUTPUT_PATH = './.nyc_output/'

const files = fs.readdirSync(NYC_OUTPUT_PATH).filter((filename) => {
  return /\.json$/.test(filename)
})

const NEW_PATH = path.join(__dirname, '../src/THIS_FILENAME_IS_A_STUB_BUT_THE_PARENT_DIRECTORY_IS_CRUCIAL.js')
files.forEach(function(filename) {
  const jsonPath = path.join(NYC_OUTPUT_PATH, filename)
  const contents = JSON.parse(fs.readFileSync(jsonPath, 'utf8'))
  Object.keys(contents).forEach((key) => {
    const val = contents[key]
    val.path = NEW_PATH
  })
  // Write the JSON back out
  fs.writeFileSync(jsonPath, JSON.stringify(contents))
})
