#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# JavaScript stuff
do_progress_quiet "Installing JavaScript Packages" \
  yarn --prefer-offline

# Python stuff
if [[ -f "./requirements.txt" || -f "./setup.py" ]]; then

  [[ -n "${VIRTUAL_ENV}" ]] || die "Not in a virtualenv"
  if [[ -f "./requirements.txt" ]]; then
    do_progress_quiet "Installing python packages" \
      pip install -r "./requirements.txt"
  else
    if [[ -f "./setup.py" ]]; then
      do_progress_quiet "Installing python packages from setup.py" \
        python setup.py install
    fi
  fi
fi

# Ruby stuff
if [[ -f "./Gemfile" ]]; then
  bundle check --path ./vendor/gems >/dev/null 2>&1  || {
    do_progress_quiet "Installing ruby gems" \
      bundle install --path ./vendor/gems --quiet --without production
  }
fi


# Load anything that is repo-specific
if [[ -f "./script/_setup.sh" ]]; then
  # shellcheck disable=SC1091
  source ./script/_setup.sh || exit 111
fi

_say "${c_green}Successfully set up${c_none}"
