#!/bin/bash

if [[ ! -f "./jspm_packages/system.js" ]]; then
  >&2 echo "It looks like you forgot to run ./script/setup first."
  exit 2
fi

source ./script/bootstrap || exit 1

$(npm bin)/jspm --log warn install || exit 3
npm install || exit 2

npm test || exit 3
