#!/bin/bash

if [[ ! -f "./jspm_packages/system.js" ]]; then
  >&2 echo "It looks like you forgot to run ./script/setup first."
  exit 1
fi

source ./script/bootstrap || exit 2

$(npm bin)/jspm --log error install || exit 3
npm --silent install || exit 4

npm --quiet test || exit 5
