#!/bin/sh
DIRNAME=`dirname "$0"`
cd "$DIRNAME/.."

NCU=`which ncu`
if [ $? -ne 0 ]
then
    echo "You need to install ncu (npm install -g npm-check-updates)"
    exit 1
fi

jspm update
ncu -u
script/setup
