#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

>&2 echo "==> Updating local setup. If you just want to upgrade 3rd-party dependencies, use ./script/upgrade instead"
sleep 2

./script/clean
./script/setup
