#!/bin/sh
DIRNAME=`dirname "$0"`
cd "$DIRNAME/.."

NCU=`which ncu`
if [ $? -ne 0 ]
then
    echo "You need to install ncu (npm install -g npm-check-updates)"
    exit 1
fi

jspm update
ncu -u
rm -rf node_modules jspm_packages
script/bootstrap
echo "CAUTION: Do not use superb 0.2.15. It causes problems in the router."
echo "Use 0.2.13, or test carefully for later versions."
