#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

>&2 echo "==> Upgrading 3rd-party dependencies. If you just want to update your local version, use ./script/update"
sleep 2

"$(npm bin)/ncu" -u
./script/setup


if [[ $(command -v yarn) ]]; then
  >&2 echo "==> Updating node packages and yarn.lock file"
  yarn upgrade || exit 2
else
  >&2 echo "==> ERROR: Could not find yarn so cannot update the yarn.lock file"
  exit 1
fi
