severity: error

linters:
    ColorKeyword:
        enabled: false

    ColorVariable:
        enabled: false

    Comment:
        enabled: false

    IdSelector:
        enabled: false

    Indentation:
        width: 4

    LeadingZero:
        enabled: true
        style: include_zero

    NestingDepth:
        max_depth: 6
        ignore_parent_selectors: true

    PropertySpelling:
        extra_properties:
            - align-items
            - grid-gap
            - grid-row-gap
            - grid-column-gap
            - grid-row-end
            - grid-row-start
            - grid-template-columns
            - grid-template-rows
            - grid-column-end
            - grid-column-start
            - grid-row-start
            - justify-items
            - place-self

    PropertyUnits:
        global: ['em', 'rem', '%', 'vw', 'vh', 'vmin', 'vmax', 's', 'fr']

    SelectorDepth:
        max_depth: 5
        ignore_parent_selectors: true
