name: Playwright

on: [pull_request]

defaults:
  run:
    working-directory: e2e_tests

jobs:
  playwright-python:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    env:
      BASE_URL: ${{ github.event.inputs.base_url }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: playwright install chromium --with-deps
    - env:
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      run: pytest --tb=long --showlocals --base-url="${BASE_URL:-https://staging.openstax.org}" --rex_user $TEST_USER_EMAIL --rex_password $TEST_USER_PASSWORD -vvv ui
